#!/bin/sh


# LiSA substitute shell script
# Copyright Lars Dornheim 1998
# E-Mail: Lars.Dornheim@Student.Uni-Magdeburg.DE
# WWW: http://graf350.urz.uni-magdeburg.de/~dornheim/index.html


# just do it

rm -f ${3}.temp
gawk "{if (index(\$0, \"$1\")!=0) {sub(\"$1.*\", \"$1\", \$0); print \$0 \"$2\" >> \"${3}.temp\"; } else print \$0 >> \"${3}.temp\"; };" $3
mv ${3}.temp ${3}
