#! /usr/bin/perl

print "first algorithm is assumed to be bounds and will be skipped";
print "\nabortions caused by \"stuck for too long\" are marked with '1'";
print "\nabortions for other reasons are marked with '0'";
$pAbort = -2;
$Reason = 0;
while ($l = <>) {
  if ($l =~ /max method\) : ([\d\.]+) \(preempt\) : ([\d\.]+) \(avrg\) : ([\d\.]+)/) {
    print "\n";
  }

  if ( $l =~ /AUTO_ALG.*problem ([\d\.]+) .*algorithm ([\d\.]+) .*objective ([\d\.]+)/) {
    if($2 == 1){
    }else{
      if($pAbort > -1){
        printf "$Reason\t";
        $pAbort = -1;
        $Reason = 0;
      }
      else{
        printf "n\\a\t";
      }
    }
  }
  
  if ( $l =~ /.*ready[=]*[\ ]+([\d]+).*/) {
    $pAbort = $1;
  }
  if( $l =~ /.*stuck for too long.*/){
    $Reason = 1;
  }
}

print "\n";

 