#! /usr/bin/perl

print "first algorithm is assumed to be bounds, no objective will be reported";
print "\nmax\tpreempt\tavrg\talgorithms";

while ($l = <>) {
  if ($l =~ /max method\) : ([\d\.]+) \(preempt\) : ([\d\.]+) \(avrg\) : ([\d\.]+)/) {
    $a = $1;
    $b = $2;
    $c = $3;
  }
  if ( $l =~ /AUTO_ALG.*algorithm ([\d\.]+) .*objective ([\d\.]+)/ ) { 
    if ($1 == 1) {
      print "\n$a\t$b\t$c\t";
    } else {
      print "$2\t";
    }
    
  }
    
}

print "\n";

