#! /usr/bin/perl

print "Lower_bounds is assumed to be the first algorithm and skipped.";
print "\nAll abortions caused by \"stuck for too long\" are indicated";
print "\nwith '1'. If the algorithm aborted for another reason it is";
print "\nindicated with a '0', the rest is marked with 'n/a'.";
print "\nAlgo 1\tAlgo 2\tAlgo 3\t...";
$pAbort = -2;
$Reason = 0;
while ($l = <>) {
  if ($l =~ /max method\) : ([\d\.]+) \(preempt\) : ([\d\.]+) \(avrg\) : ([\d\.]+)/) {
    print "\n";
  }

  if ( $l =~ /AUTO_ALG.*problem ([\d\.]+) .*algorithm ([\d\.]+) .*objective ([\d\.]+)/) {
    if($2 == 1){
    }else{
      if($pAbort > -1){
        printf "$Reason\t";
        $pAbort = -1;
        $Reason = 0;
      }
      else{
        printf "n\\a\t";
      }
    }
  }
  
  if ( $l =~ /.*ready=[\ ]+([\d]+).*/) {
    $pAbort = $1;
  }
  if( $l =~ /.*stuck for too long.*/){
    $Reason = 1;
  }
}

print "\n";

 