# stolen from:
# LiSA Sample Algorithm Makefile
# Copyright Lars Dornheim 1998, 2002
# E-Mail: Lars.Dornheim@Student.Uni-Magdeburg.DE
# WWW: http://graf350.urz.uni-magdeburg.de/~dornheim/index.html

# ------------------------------------------------------------------------------

# LiSA part: lower_bounds

PROGRAMNAME=lower_bounds

# ------------------------------------------------------------------------------

TOPPROGRAMPATH=../../..

# ------------------------------------------------------------------------------

include ../Make.Utility


