# LiSA Algorithm Module Makefile
# Copyright Lars Dornheim 1998, 2002
# E-Mail: Lars.Dornheim@Student.Uni-Magdeburg.DE
# WWW: http://graf350.urz.uni-magdeburg.de/~dornheim/index.html

# ------------------------------------------------------------------------------

# LiSA part: reducing_set

PROGRAMNAME=reducing_set

# ------------------------------------------------------------------------------

TOPPROGRAMPATH=../../..

# ------------------------------------------------------------------------------

include ../Make.Algorithm

